server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    #表示是否注册自身到eureka服务器，因为当前这个应用就是eureka服务器，没必要注册自身#
    register-with-eureka: false
    #是否从eureka服务器获取注册信息，同上，这里不需要#
    fetch-registry: false
    #设置eureka服务器所在的地址#
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
