eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: erueka-feign
  zipkin:
    base-url: http://localhost:9411
feign:
  hystrix:
    enabled: true